'use client'

import Link from 'next/link'
import Image from 'next/image'
import { Search, SlidersHorizontal, ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react'
import { useMemo, useState } from 'react'
import { products } from '@/lib/products'

const families = ['All families', 'Fresh', 'Floral', 'Woody', 'Oriental']
const zodiac = ['All signs', 'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces']

export default function CollectionPage() {
  const [query, setQuery] = useState(''), [family, setFamily] = useState('All families'), [sign, setSign] = useState('All signs'), [page, setPage] = useState(1), [advanced, setAdvanced] = useState(false)
  const filtered = useMemo(() => products.filter((p) => `${p.name} ${p.title} ${p.notes} ${p.description}`.toLowerCase().includes(query.toLowerCase()) && (family === 'All families' || p.family === family) && (sign === 'All signs' || p.zodiac.includes(sign))), [query, family, sign])
  const perPage = 8
  const visible = filtered.slice((page - 1) * perPage, page * perPage), pages = Math.max(1, Math.ceil(filtered.length / perPage))
  const update = (fn: () => void) => { fn(); setPage(1) }
  return <main className="min-h-screen bg-[#050b13] text-[#eee8da] selection:bg-[#c19a52] selection:text-[#050b13]">
    <header className="mx-auto flex max-w-7xl items-center justify-between border-b border-[#66532f] px-6 py-6 lg:px-12"><Link href="/" className="inline-flex items-center" aria-label="HORUSCOPE Home"><Image src="/HL WMWT (G).png" alt="HORUSCOPE" width={150} height={32} priority className="h-7 w-auto object-contain transition-opacity duration-300 hover:opacity-85" /></Link><Link href="/" className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a7a39a] hover:text-[#f0cc7d]">Back to journal</Link></header>
    <section className="mx-auto max-w-7xl px-6 pb-16 pt-20 lg:px-12 lg:pt-28"><p className="mb-5 font-mono text-[10px] uppercase tracking-[.2em] text-[#c19a52]">The archive / 12 compositions</p><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><h1 className="max-w-3xl font-serif text-6xl leading-[.9] tracking-[-.04em] sm:text-8xl">A fragrance<br/><em className="text-[#c19a52]">for your orbit.</em></h1><p className="max-w-xs font-mono text-xs uppercase leading-6 tracking-[.12em] text-[#a7a39a]">Twelve civilizations. Twelve zodiac signals. Small-batch compositions for the stories written into your skin.</p></div></section>
    <section className="mx-auto max-w-7xl border-y border-[#66532f] px-6 py-5 lg:px-12"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><label className="flex flex-1 items-center gap-3 border-b border-[#66532f] pb-3"><Search size={17} className="text-[#c19a52]"/><span className="sr-only">Search fragrances</span><input value={query} onChange={(e) => update(() => setQuery(e.target.value))} placeholder="Search by name, note or atmosphere" className="w-full bg-transparent font-mono text-xs uppercase tracking-[.12em] outline-none placeholder:text-[#a7a39a]"/></label><select value={family} onChange={(e) => update(() => setFamily(e.target.value))} className="bg-[#091522] px-3 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-[#eee8da] outline-none"><option>{families[0]}</option>{families.slice(1).map((item) => <option key={item}>{item}</option>)}</select><button onClick={() => setAdvanced(!advanced)} className="flex items-center gap-2 border border-[#66532f] px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] hover:border-[#f0cc7d]"><SlidersHorizontal size={14}/> Advanced filter</button></div>{advanced && <div className="mt-5 flex flex-wrap gap-2 border-t border-[#66532f] pt-5"><span className="mr-2 py-2 font-mono text-[10px] uppercase tracking-[.16em] text-[#c19a52]">Your zodiac</span>{zodiac.map((item) => <button key={item} onClick={() => update(() => setSign(item))} className={`border px-3 py-2 font-mono text-[10px] uppercase tracking-[.1em] ${sign === item ? 'border-[#f0cc7d] text-[#f0cc7d]' : 'border-[#66532f] text-[#a7a39a]'}`}>{item}</button>)}</div>}</section>
    <section className="mx-auto max-w-7xl px-6 py-12 lg:px-12"><div className="mb-6 flex justify-between font-mono text-[10px] uppercase tracking-[.15em] text-[#a7a39a]"><span>{filtered.length} compositions found</span><span>{sign !== 'All signs' ? `Aligned with ${sign}` : 'The complete archive'}</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visible.map((p) => <Link href={`/collection/${p.slug}`} key={p.slug} className="group border border-[#66532f] bg-[#091522] transition-transform duration-500 hover:-translate-y-2"><div className="relative aspect-[4/5] overflow-hidden"><img src={p.image} alt={`${p.name} perfume`} className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100"/><span className="absolute left-4 top-4 font-mono text-[10px] tracking-[.15em] text-[#f0cc7d]">{p.code}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-serif text-2xl">{p.name}</h2><p className="mt-1 font-mono text-[10px] uppercase tracking-[.12em] text-[#c19a52]">{p.title}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[.12em] text-[#a7a39a]">{p.notes}</p></div><ArrowUpRight size={17} className="text-[#c19a52]"/></div><div className="mt-7 flex justify-between font-mono text-xs"><span>{p.zodiac.join(' · ')}</span><span>₦{p.price50ml.toLocaleString()}</span></div></div></Link>)}</div>{visible.length === 0 && <div className="border border-[#66532f] py-20 text-center font-serif text-2xl text-[#a7a39a]">No atmosphere matches your search.</div>}<div className="mt-12 flex items-center justify-center gap-5"><button aria-label="Previous page" disabled={page === 1} onClick={() => setPage(page - 1)} className="border border-[#66532f] p-3 disabled:opacity-30"><ChevronLeft size={16}/></button><span className="font-mono text-xs tracking-[.2em] text-[#c19a52]">0{page} / 0{pages}</span><button aria-label="Next page" disabled={page === pages} onClick={() => setPage(page + 1)} className="border border-[#66532f] p-3 disabled:opacity-30"><ChevronRight size={16}/></button></div></section>
    <footer className="flex flex-col items-center justify-center gap-3 border-t border-[#66532f] px-6 py-10 text-center"><Image src="/HL WMWT (G).png" alt="HORUSCOPE" width={140} height={30} className="h-6 w-auto object-contain opacity-90" /><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#a7a39a]">Stories, bottled.</p></footer>
  </main>
}
