'use client'

import { useEffect, useRef, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowDown, ArrowUpRight, Menu, X, Sparkles } from 'lucide-react'
import BagButton from '@/components/BagButton'
import { products } from '@/lib/products'

const signs = [
  ['Aries', '21 Mar — 19 Apr', 'The Pioneer'], ['Taurus', '20 Apr — 20 May', 'The Connoisseur'], ['Gemini', '21 May — 20 Jun', 'The Keeper'],
  ['Cancer', '21 Jun — 22 Jul', 'The Beloved'], ['Leo', '23 Jul — 22 Aug', 'The Sovereign'], ['Virgo', '23 Aug — 22 Sep', 'The Artisan'],
  ['Libra', '23 Sep — 22 Oct', 'The Seeker'], ['Scorpio', '23 Oct — 21 Nov', 'The Enigma'], ['Sagittarius', '22 Nov — 21 Dec', 'The Explorer'],
  ['Capricorn', '22 Dec — 19 Jan', 'The Architect'], ['Aquarius', '20 Jan — 18 Feb', 'The Visionary'], ['Pisces', '19 Feb — 20 Mar', 'The Dreamer'],
]
const glyphs = ['♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓']
function Label({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false), [selectedSign, setSelectedSign] = useState('Leo'), [active, setActive] = useState(0), [quizOpen, setQuizOpen] = useState(false), [step, setStep] = useState(0), [result, setResult] = useState('')
  const root = useRef<HTMLElement>(null)
  useEffect(() => { const onScroll = () => root.current?.style.setProperty('--scroll', `${window.scrollY * .08}px`); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  const move = (e: React.PointerEvent<HTMLElement>) => { const r = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty('--mx', `${(e.clientX - r.left) / r.width * 100}%`); e.currentTarget.style.setProperty('--my', `${(e.clientY - r.top) / r.height * 100}%`) }
  const sign = signs.find(s => s[0] === selectedSign) ?? signs[0]
  const questions = [['Where do you feel most like yourself?', ['In the sun', 'Near water', 'Among trees', 'Under stars']], ['Choose a texture.', ['Warm stone', 'Wet silk', 'Raw wood', 'Black velvet']], ['Your ideal hour?', ['Golden hour', 'Blue hour', 'Midnight', 'First light']]]
  return <main ref={root} className="horuscope-shell">
    <div className="scroll-line" aria-hidden="true" />
    <header className="site-header"><a href="#top" className="wordmark" aria-label="HORUSCOPE Home"><Image src="/HL WMWT (G).png" alt="HORUSCOPE" width={160} height={34} priority className="h-8 w-auto object-contain transition-opacity duration-300 hover:opacity-85" /></a><nav className="desktop-nav" aria-label="Primary navigation"><a href="#collection">Zodiac</a><a href="/collection">Collection</a><a href="#journal">Journal</a></nav><BagButton className="bag-button" /><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>
    {menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation"><a href="#collection" onClick={() => setMenuOpen(false)}>Zodiac</a><a href="/collection" onClick={() => setMenuOpen(false)}>Collection</a><a href="#journal" onClick={() => setMenuOpen(false)}>Journal</a></nav>}
    <section className="hero-frame" id="top" onPointerMove={move}><div className="hero-sky" /><div className="hero-copy"><Label>.</Label><h1 className="hero-title">The universe,<br /><em>bottled.</em></h1><p>Fragrance for the signs, seasons and stories written into your skin.</p><a className="gold-button" href="#archive">Explore the collection <ArrowUpRight size={14} /></a></div><div className="hero-image"><Image src="/images/horuscope-hero.png" alt="Black HORUSCOPE fragrance bottle in a celestial landscape" fill priority sizes="(max-width: 800px) 100vw, 70vw" /></div><div className="hero-orbit" aria-hidden="true" /><span className="hero-coordinate">48°51' N<br />2°21' E</span></section>
    <section className="destination-grid"><a href="#collection" className="destination-card card-zodiac"><span>Zodiac</span><strong>12 signs.<br />12 stories.</strong><small>Discover <ArrowUpRight size={12} /></small></a><a href="#journal" className="destination-card card-landmarks"><span>Landmarks</span><strong>Civilizations,<br />immortalized in scent.</strong><small>Discover <ArrowUpRight size={12} /></small></a><a href="#archive" className="destination-card card-relics"><span>Relics</span><strong>Handcrafted art.<br />Limited to eternity.</strong><small>Discover <ArrowUpRight size={12} /></small></a></section>
    <section className="manifesto"><div><Label>01 / A point of origin</Label><h2>Every bottle<br />holds a <em>world.</em></h2></div><div className="manifesto-copy"><p>HORUSCOPE is an olfactive archive of the invisible forces that shape us. Twelve compositions, each a different civilization, a different atmosphere. Find the one that feels like it has been waiting for you.</p><a className="text-link" href="#archive">Read our story <ArrowUpRight size={15} /></a></div></section>
    <section className="zodiac-section" id="collection"><div className="section-heading"><div><Label>02 / Your constellation</Label><h2>Choose your <em>signal.</em></h2></div><p>There is no right answer.<br />Only the one that stays.</p></div><div className="zodiac-grid">{signs.map(([name, dates, title], i) => <button key={name} className={`zodiac-item ${selectedSign === name ? 'is-selected' : ''}`} onClick={() => setSelectedSign(name)}><span className="zodiac-glyph">{glyphs[i]}</span><span><strong>{name}</strong><small>{dates}</small></span><i>{title}</i></button>)}</div><div className="selected-signal"><span>Your signal</span><strong>{sign[0]}</strong><p>{sign[2]} — a signature composition, chosen not by horoscope but by the part of you that recognizes itself.</p></div></section>
    <section className="fragrance-section" id="archive"><div className="section-heading"><div><Label>03 / The archive</Label><h2>Twelve ways to<br /><em>leave a trace.</em></h2></div><p>Composed in Paris.<br />Finished by hand.</p></div><div className="fragrance-layout"><div className="fragrance-list">{products.map((p, i) => <Link href={`/collection/${p.slug}`} key={p.slug} className={`fragrance-row ${active === i ? 'is-active' : ''}`} onMouseEnter={() => setActive(i)}><span>{p.code}</span><strong>{p.name}</strong><small>{p.notes}</small><ArrowUpRight size={16} /></Link>)}</div><div className="fragrance-detail" onPointerMove={move}><div className="detail-image"><Image src={products[active].image} alt={`${products[active].name} fragrance bottle`} fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div className="detail-copy"><Label>Selected composition / {products[active].zodiac[0]}</Label><h3>{products[active].name}: <em>{products[active].title}</em></h3><p>{products[active].description}</p><span className="note-line">{products[active].notes}</span><Link href={`/collection/${products[active].slug}`} className="outline-button">Discover {products[active].name} <ArrowUpRight size={15} /></Link></div></div></div></section>
    <section className="quiz-section"><div className="quiz-art"><span>Find the atmosphere<br />that finds you.</span><Sparkles size={22} /></div><div className="quiz-copy"><Label>04 / A private reading</Label><h2>What does<br /><em>your skin</em> remember?</h2><p>Answer three instinctive questions. We will return a fragrance, not a personality type.</p><button className="gold-button" onClick={() => { setQuizOpen(true); setStep(0); setResult('') }}>Begin your reading <ArrowUpRight size={15} /></button></div></section>
    <section className="craft-section"><div className="craft-image"><Image src="/images/horuscope-craft.png" alt="Perfumer measuring amber liquid at an atelier workbench" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div className="craft-copy"><Label>05 / The hand behind it</Label><h2>Made slowly.<br /><em>Worn closely.</em></h2><p>Small batches. Precious materials. Every formula is rested, tested and filled by a single pair of hands. Each composition is named after a civilization and aligned with a zodiac sign — not as prescription, but as resonance.</p><a className="text-link" href="#journal">Inside the atelier <ArrowUpRight size={15} /></a></div></section>
    <section className="journal-section" id="journal"><div className="section-heading"><div><Label>06 / Field notes</Label><h2>From the <em>journal.</em></h2></div><a className="text-link" href="#journal">View all notes <ArrowUpRight size={15} /></a></div><div className="journal-grid"><article><span>01 — On material</span><h3>The quiet intelligence of cedar.</h3><a href="#journal">Read note <ArrowUpRight size={14} /></a></article><article><span>02 — On ritual</span><h3>Why scent belongs to the hour before sleep.</h3><a href="#journal">Read note <ArrowUpRight size={14} /></a></article><article><span>03 — On place</span><h3>A field guide to the Mediterranean after rain.</h3><a href="#journal">Read note <ArrowUpRight size={14} /></a></article></div></section>
    <footer className="site-footer"><div className="footer-brand"><Image src="/HL WMWT (G).png" alt="HORUSCOPE" width={160} height={34} className="h-8 w-auto object-contain" /><p>Stories, bottled.</p></div><div className="footer-links"><a href="#collection">Shop collection</a><a href="#journal">Contact</a><a href="#journal">Instagram</a></div><p className="copyright">© 2026 HORUSCOPE<br />Made in small numbers.</p></footer>
    {quizOpen && <div className="quiz-modal" role="dialog" aria-modal="true" aria-labelledby="quiz-title"><div className="quiz-panel"><button className="close-quiz" onClick={() => setQuizOpen(false)} aria-label="Close reading"><X size={20} /></button>{step < questions.length ? <><Label>Private reading / 0{step + 1}</Label><h2 id="quiz-title">{questions[step][0]}</h2><div className="quiz-options">{(questions[step][1] as string[]).map(a => <button key={a} onClick={() => { if (step === 2) { setResult(a); setStep(3) } else setStep(step + 1) }}>{a}<ArrowUpRight size={15} /></button>)}</div></> : <><Label>Your atmosphere</Label><h2 id="quiz-title">{result === 'Under stars' || result === 'Black velvet' || result === 'Midnight' ? 'Eiffel: The Enigma' : result === 'Near water' || result === 'Wet silk' ? 'Pont du Gard: The Dreamer' : result === 'Among trees' || result === 'Raw wood' ? 'Machu Picchu: The Artisan' : 'Great Wall: The Pioneer'}</h2><p className="quiz-result">A composition chosen for the part of you that trusts instinct before explanation.</p><button className="gold-button" onClick={() => setQuizOpen(false)}>Explore your fragrance <ArrowUpRight size={15} /></button></>}</div></div>}
  </main>
}
