export type Product = {
  slug: string
  code: string
  name: string
  title: string
  price: number
  price50ml: number
  price100ml: number
  zodiac: string[]
  family: string
  notes: string
  description: string
  story: string
  origin: string
  personalization: string
  image: string
}

export const products: Product[] = [
  {
    slug: 'great-wall',
    code: 'ARIES / 01',
    name: 'Great Wall',
    title: 'The Pioneer',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Aries'],
    family: 'Fresh',
    notes: 'Ginger · Leather · Sandalwood',
    description: 'A bold, unyielding composition for those who move first and never look back. Great Wall opens with the sharp crack of fresh ginger against sun-warmed leather, then settles into a deep sandalwood base that feels both ancient and unstoppable. It is the scent of crossing a threshold no one else dared approach — warm, direct, and utterly certain.',
    story: 'For the one who builds what others only imagine. Great Wall begins with the confidence of ginger snapping through cold air, wrapped in the quiet authority of aged leather. As it warms against the skin, sandalwood rises — not as a whisper, but as a foundation. This is a fragrance for those who lead without announcing it, whose presence alone shifts the room.',
    origin: 'Inspired by the silent strength of stone fortifications stretching across mountain ridges, built by hands that understood permanence.',
    personalization: 'Great Wall adapts to the wearer\'s body heat — on warmer skin, the ginger sharpens and the leather becomes more pronounced. On cooler skin, the sandalwood takes precedence, creating a meditative, grounded trail. Apply to the chest and wrists for maximum projection.',
    image: '/products/A.png',
  },
  {
    slug: 'taj-mahal',
    code: 'CANCER / 02',
    name: 'Taj Mahal',
    title: 'The Beloved',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Cancer'],
    family: 'Floral',
    notes: 'Rose · Saffron · Musk',
    description: 'A love letter written in white marble and evening light. Taj Mahal unfolds like a memory you keep returning to — the deep, honeyed warmth of saffron-threaded rose, softened by a veil of skin musk that feels like being held. It is both monumental and intimate, a fragrance that remembers everything and forgives without being asked.',
    story: 'For the one who feels everything deeply and protects what they love fiercely. Taj Mahal opens with the impossible richness of rose absolute steeped in saffron — dark, golden, alive. As hours pass, white musk emerges like a hand reaching through shadow, warm and certain. This is not a fragrance you wear. It is one you carry.',
    origin: 'Composed from the memory of marble gardens at dusk, where the air holds both the sweetness of blooming flowers and the weight of centuries of devotion.',
    personalization: 'Taj Mahal blooms differently on each wearer — the rose can appear more powdery or more alive depending on skin chemistry. The saffron deepens with body warmth, creating a personal golden aura. Best applied to pulse points where blood runs close to the surface.',
    image: '/products/B.png',
  },
  {
    slug: 'colosseum',
    code: 'TAURUS / 03',
    name: 'Colosseum',
    title: 'The Connoisseur',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Taurus'],
    family: 'Woody',
    notes: 'Tobacco · Oud · Amber',
    description: 'The quiet authority of something that has survived everything. Colosseum is a fragrance of deep pleasures — the richness of aged tobacco leaf, the resonant darkness of oud, and the warm, resinous glow of amber that feels like late afternoon light on ancient stone. It is unhurried, deliberate, and impossible to ignore.',
    story: 'For the one who understands that true luxury is patience. Colosseum opens with the smooth, almost sweet density of tobacco that has been cured by time, not heat. Oud rises slowly beneath it — not sharp, but deep, like the echo of footsteps in a vast, empty hall. Amber holds everything together, warm as a hand on your shoulder.',
    origin: 'Drawn from the atmosphere of Roman afternoon — the warmth of stone that has absorbed centuries of sun, the richness of smoke drifting through arched corridors.',
    personalization: 'Colosseum develops slowly on skin, revealing new facets over several hours. The tobacco note can appear more sweet or more dry depending on pH. The oud grows warmer with body heat. Apply generously to the neck and chest for a scent that evolves throughout the day.',
    image: '/products/C.png',
  },
  {
    slug: 'alexandria',
    code: 'GEMINI / 04',
    name: 'Alexandria',
    title: 'The Keeper',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Gemini'],
    family: 'Fresh',
    notes: 'Neroli · Incense · Cedar',
    description: 'A library of light and smoke, held in a single breath. Alexandria is the scent of accumulated knowledge — the bright, almost citrus clarity of neroli opening like a page turned, the sacred hush of incense curling through ancient halls, and cedar standing steady as the shelves that hold everything worth remembering.',
    story: 'For the one who collects ideas the way others collect objects. Alexandria begins with neroli so vivid it feels like sunlight caught in glass. Incense follows — not heavy, but present, like the memory of a ritual you once witnessed and never forgot. Cedar arrives last, grounding everything in the quiet certainty of things that endure.',
    origin: 'Inspired by the legendary collection of scrolls and the Mediterranean light that poured through the windows of the ancient library.',
    personalization: 'Alexandria is remarkably adaptive — the neroli brightens in daylight, while the incense deepens in evening warmth. On some wearers, the cedar becomes the dominant note after several hours. Apply to the wrists and behind the ears for a composition that shifts with the day.',
    image: '/products/D.png',
  },
  {
    slug: 'karnak',
    code: 'LEO / 05',
    name: 'Karnak',
    title: 'The Sovereign',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Leo'],
    family: 'Oriental',
    notes: 'Oud · Gold Amber · Myrrh',
    description: 'The weight of gold and the gravity of ritual. Karnak is a fragrance of absolute presence — oud burnished to a deep, almost metallic richness, amber that glows like molten resin, and myrrh carrying the solemn sweetness of offerings made to something greater than yourself. It does not ask for attention. It commands it.',
    story: 'For the one who was never meant to blend in. Karnak opens with oud at its most regal — dark, complex, and unapologetically bold. Gold amber wraps around it like light on a pharaoh\'s crown, while myrrh adds a sacred dimension that elevates the composition from luxury to ceremony. This is a fragrance for those who understand that presence is a choice.',
    origin: 'Born from the atmosphere of temple columns at sunset, where stone becomes gold and the air itself feels charged with ancient intention.',
    personalization: 'Karnak intensifies with body heat, making it a fragrance that grows more commanding throughout the evening. The oud can appear more smoky or more woody depending on skin chemistry. Best worn boldly — apply to the chest, neck, and inside of elbows.',
    image: '/products/E.png',
  },
  {
    slug: 'machu-picchu',
    code: 'VIRGO / 06',
    name: 'Machu Picchu',
    title: 'The Artisan',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Virgo'],
    family: 'Woody',
    notes: 'Vetiver · Green Tea · Moss',
    description: 'Precision made invisible. Machu Picchu is the scent of elevated craft — vetiver pulled taut as a wire, green tea holding its breath between sweetness and austerity, and moss growing in the cracks of something built to last. It is clean without being sterile, natural without being naive, and deeply, quietly satisfying.',
    story: 'For the one who finds beauty in the thing done right. Machu Picchu opens with vetiver at its most refined — earthy but not heavy, structured but never rigid. Green tea adds a luminous clarity, like morning light on wet stone. Moss follows, softening the edges with the patient green of things that grow slowly and never fall.',
    origin: 'Composed from the atmosphere of high-altitude stone terraces, where clouds pass through ruins and the air tastes of earth, water, and time.',
    personalization: 'Machu Picchu is remarkably consistent across skin types — its precision means it reads clearly on everyone. The green tea note can appear more bright or more herbal depending on body chemistry. Apply to the inner wrists and the base of the throat for a clean, lasting trail.',
    image: '/products/F.png',
  },
  {
    slug: 'artemis',
    code: 'LIBRA / 07',
    name: 'Artemis',
    title: 'The Seeker',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Libra'],
    family: 'Fresh',
    notes: 'Jasmine · White Musk · Silver Birch',
    description: 'The pursuit of beauty without destination. Artemis is a composition of elegant tension — jasmine so pale it feels like moonlight on water, white musk creating ahalo of clean warmth, and silver birch adding a cool, almost architectural edge. It is a fragrance that never resolves, and that is precisely its power.',
    story: 'For the one who is drawn to what is just out of reach. Artemis opens with jasmine at its most ethereal — not the heavy, narcotic kind, but the white, almost transparent variety that smells like a question. White musk follows, creating a luminous field around the wearer. Silver birch arrives last, adding the cool precision of something seen from a distance.',
    origin: 'Inspired by the moment of crossing a threshold into a forest clearing — the shift from shadow to silver light, from noise to a profound, ringing silence.',
    personalization: 'Artemis is a chameleon on skin — it can appear more floral or more woody depending on the wearer\'s natural chemistry. The jasmine opens differently in warm versus cool environments. Apply to the pulse points and let the composition find its own balance.',
    image: '/products/G.png',
  },
  {
    slug: 'eiffel',
    code: 'SCORPIO / 08',
    name: 'Eiffel',
    title: 'The Enigma',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Scorpio'],
    family: 'Oriental',
    notes: 'Black Rose · Leather · Patchouli',
    description: 'A secret told in iron and velvet. Eiffel is a fragrance of contradiction — black rose unfolding in darkness, leather wrapped around something soft and unspoken, and patchouli rising like smoke from a fire no one remembers lighting. It is glamorous without being decorative, intense without being loud, and entirely, unapologetically itself.',
    story: 'For the one who reveals only what they choose. Eiffel opens with black rose at its most arresting — dark, velvety, and faintly dangerous. Leather follows, structured and cool, like the iron framework of something built to touch clouds. Patchouli deepens everything, adding an earthy richness that lingers long after the wearer has left the room.',
    origin: 'Drawn from Parisian nights where the city becomes a stage — the interplay of shadow and light on iron lattice, the whisper of heels on wet pavement.',
    personalization: 'Eiffel intensifies in enclosed spaces, making it a fragrance that announces your presence before you speak. The black rose note can appear more sweet or more dark depending on skin pH. Best worn in the evening — apply to the neck, chest, and inside of the wrists.',
    image: '/products/H.png',
  },
  {
    slug: 'timbuktu',
    code: 'SAGITTARIUS / 09',
    name: 'Timbuktu',
    title: 'The Explorer',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Sagittarius'],
    family: 'Woody',
    notes: 'Saffron · Cardamom · Sandalwood',
    description: 'The horizon line where spice roads meet the sky. Timbuktu is a fragrance of movement and discovery — saffron burning gold through cool air, cardamom cracking open like a door, and sandalwood stretching endlessly forward, warm and certain. It is restless without being anxious, warm without being heavy, and always, always heading somewhere.',
    story: 'For the one who is never quite where they were yesterday. Timbuktu opens with saffron at its most vivid — not the subtle, culinary kind, but the deep, almost electric gold that stains everything it touches. Cardamom follows, sharp and exhilarating, like the first breath of a new city. Sandalwood arrives last, creating a warm, unwavering path that extends far beyond the visible.',
    origin: 'Composed from the memory of trade routes and desert crossings — the heat of spice markets, the cool of evening shade, and the vast, open silence between stars.',
    personalization: 'Timbuktu is remarkably resilient — it holds its character in both heat and cold, making it an excellent travel companion. The saffron brightens in warm weather while the sandalwood deepens in cold. Apply liberally for a scent that travels with you.',
    image: '/products/I.png',
  },
  {
    slug: 'giza',
    code: 'CAPRICORN / 10',
    name: 'Giza',
    title: 'The Architect',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Capricorn'],
    family: 'Woody',
    notes: 'Amber · Oud · Cedarwood',
    description: 'The geometry of something built to outlast empires. Giza is a fragrance of absolute structure — amber compressed into a warm, golden stone, oud providing the dark, resonant foundation, and cedarwood rising in precise, unwavering columns. It is severe without being cold, monumental without being overwhelming, and built to endure.',
    story: 'For the one who thinks in decades, not days. Giza opens with amber at its most concentrated — not sweet, but dense, like sunlight absorbed into limestone over millennia. Oud follows, dark and structural, providing the invisible framework that holds everything upright. Cedarwood arrives last, clean and architectural, like the last course laid on a pyramid.',
    origin: 'Inspired by the impossible precision of ancient engineering — the alignment of stone blocks, the geometry of shadow, and the silence of something that has watched civilizations rise and fall.',
    personalization: 'Giza is remarkably stable on skin — its architectural nature means it maintains its structure regardless of body chemistry. The amber warms with heat while the oud holds firm. Apply to the chest and wrists for a scent that projects quiet authority.',
    image: '/products/J.png',
  },
  {
    slug: 'atlantis',
    code: 'AQUARIUS / 11',
    name: 'Atlantis',
    title: 'The Visionary',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Aquarius'],
    family: 'Fresh',
    notes: 'Sea Salt · Driftwood · Ambergris',
    description: 'The sound of water remembering a civilization. Atlantis is a fragrance of submerged beauty — sea salt crystallized on skin, driftwood smoothed by impossible currents, and ambergris carrying the mineral, almost metallic sweetness of something lost and found and lost again. It is cool without being distant, elemental without being primitive.',
    story: 'For the one who sees what others have stopped looking for. Atlantis opens with sea salt so real it feels like a tide going out — clean, mineral, and faintly luminous. Driftwood follows, pale and weathered, carrying the memory of journeys across impossible distances. Ambergris arrives last, adding a depth that suggests not just the ocean, but everything the ocean has swallowed.',
    origin: 'Composed from the atmosphere of deep water and lost places — the pressure of depths where light barely reaches, the cool salt of currents that have traveled for centuries.',
    personalization: 'Atlantis is profoundly affected by body temperature — on warm skin, the sea salt brightens and the ambergris becomes more mineral. On cool skin, the driftwood takes precedence. Apply to the neck and behind the ears for a scent that feels like a second skin.',
    image: '/products/K.png',
  },
  {
    slug: 'pont-du-gard',
    code: 'PISCES / 12',
    name: 'Pont du Gard',
    title: 'The Dreamer',
    price: 44700,
    price50ml: 44700,
    price100ml: 74700,
    zodiac: ['Pisces'],
    family: 'Floral',
    notes: 'Iris · Fig Leaf · Water Lily',
    description: 'The architecture of a daydream. Pont du Gard is a fragrance of liquid grace — iris suspended between earth and sky, fig leaf adding a cool, green breath of something half-remembered, and water Lily floating on the surface of something deep and still. It is gentle without being fragile, complex without being confusing, and endlessly, quietly beautiful.',
    story: 'For the one who lives partially in another world. Pont du Gard opens with iris at its most poetic — powdery, cool, and faintly violet, like the color of early morning seen through water. Fig leaf follows, adding a green, almost milky freshness that feels like a hand trailing through a stream. Water Lily arrives last, completing the composition with afloat, luminous grace.',
    origin: 'Inspired by the moment water passes through ancient stone — the marriage of the organic and the architectural, the way nature softens everything it touches.',
    personalization: 'Pont du Gard is perhaps the most personal of all the compositions — it adapts profoundly to the wearer\'s skin chemistry, appearing more floral or more green depending on pH. The iris can shift from powdery to almost metallic. Apply to the wrists and let the composition find its own expression.',
    image: '/products/L.png',
  },
]

export function getProduct(slug: string) { return products.find((product) => product.slug === slug) }
